apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijezet-spring-backend
  namespace: dijezetapp
  labels:
    app: dijezet-spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijezet-spring-backend
  template:
    metadata:
      labels:
        app: dijezet-spring-backend
    spec:
      containers:
        - name: dijezet-spring-backend
          image: ghcr.io/karl255/tvz-naprednajava-projekt:f29c42e9594783d5c2149e3fe683d1d40e1f617b
          ports:
            - containerPort: 8080
