apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijezet-spring-backend
  namespace: dijezetapp
  labels:
    app: dijezet-spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijezet-spring-backend
  template:
    metadata:
      labels:
        app: dijezet-spring-backend
    spec:
      containers:
        - name: dijezet-spring-backend
          image: ghcr.io/karl255/tvz-naprednajava-projekt:4f3fb829823016597cd4d167e8ffda1a7f01e21f
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s