apiVersion: v1
kind: Service
metadata:
  name: dijezet-spring-backend-service
  namespace: dijezetapp
spec:
  selector:
    app: dijezet-spring-backend
  ports:
    - protocol: TCP
      targetPort: 8080
      nodePort: 32000
      port: 1234
  type: NodePort
