apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijezet-frontend
  namespace: dijezetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijezet-frontend
  template:
    metadata:
      labels:
        app: dijezet-frontend
    spec:
      containers:
        - name: nginx
          image: ghcr.io/karl255/dijezet-frontend:f29c42e9594783d5c2149e3fe683d1d40e1f617b
          ports:
            - containerPort: 80
