apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijezet-frontend
  namespace: dijezetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijezet-frontend
  template:
    metadata:
      labels:
        app: dijezet-frontend
    spec:
      containers:
        - name: nginx
          image: ghcr.io/karl255/dijezet-frontend:77504fa617b9aa9910d9e38efd10bf21abc343fc
          ports:
            - containerPort: 80
