apiVersion: v1
kind: Service
metadata:
  name: dijezet-frontend
  namespace: dijezetapp
spec:
  type: NodePort
  selector:
    app: dijezet-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002
