create table users
(
    id              bigint generated by default as identity,
    hashed_password varchar(255),
    username        varchar(255),
    primary key (id)
);

create table line
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table station
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table pin
(
    id         bigint generated by default as identity,
    latitude   numeric(10, 8),
    longitude  numeric(10, 8),
    line_id    bigint,
    station_id bigint,
    user_id    bigint,
    primary key (id)
);

alter table if exists pin
    add constraint pin_line_fk foreign key (line_id) references line,
    add constraint pin_station_fk foreign key (station_id) references station,
    add constraint pin_user_fk foreign key (user_id) references users;

create table comment
(
    id                bigint generated by default as identity,
    content           varchar(255),
    created_at        timestamp(6),
    issue_type        smallint check (issue_type between 0 and 4),
    parent_comment_id bigint,
    pin_id            bigint,
    user_id           bigint,
    primary key (id)
);

alter table if exists comment
    add constraint parent_comment_fk foreign key (parent_comment_id) references comment,
    add constraint comment_pin_fk foreign key (pin_id) references pin,
    add constraint comment_user_fk foreign key (user_id) references users;