CREATE TABLE "user-refresh-tokens"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT,
    refresh_token VARCHAR(255),
    expires_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT "pk_user-refresh-tokens" PRIMARY KEY (id)
);

ALTER TABLE "user-refresh-tokens"
    ADD CONSTRAINT "FK_USER-REFRESH-TOKENS_ON_USER" FOREIGN KEY (user_id) REFERENCES users (id);