apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijezet-postgres
  namespace: dijezetapp
  labels:
    app: dijezet-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijezet-postgres
  template:
    metadata:
      labels:
        app: dijezet-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: di-je-zet-db
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
